### ISSUE TITLE
Security issue: alle GETs moeten POSTs worden

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-indicatie#11]
In de query strings van de GETs requests zit allemaal gevoelige persoonlijk info. Dat betreft niet alleen BSNs maar ook allerlei ids waarmee je vervolgens persoonlijke informatie kan ophalen.

Dit soort GET requests wordt overal vastgelegd in diverse server logging en vormt daarmee een security risico.

Daarom is het niet acceptabel dat er GET requests gebruikt worden. Svp omzetten naar POST requests.

(NB: dit heeft niets te maken met autorisatie issues).

https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url

**Comment by hilkojacobse** [comment]
Levert inderdaad minder BSN's in logfiles  op. Als dit voor jullie weinig impact heeft passen we het aan.

**Comment by michielgkalkman** [comment]
Graag aanpassen. Ik verwacht weinig impact aan onze kant.

**Comment by hilkojacobse** [comment]
@michielgkalkman Ik realiseer me net dat we "uiteindelijk" pseudoniemen willen gaan gebruiken in de uitwisseling tussen netwerkpunt en dataservice. In dat geval gaan er dus geen BSN's meer in de URL mee. Verandert dat de zaak wat jou betreft of zou je dan nog steeds adviseren om met post's te werken?

**Comment by michielgkalkman** [comment]
Ik zou nog steeds met POSTs willen werken. "uiteindelijk" kan nog heel lang duren. We hebben hier iig nog geen idee hoe die pseudoniemen moeten gaan werken. Verder wil je ook wlzindicatieids niet prijs geven.

We hebben het hier ook PII dus dan ben ik liever te veilig dan niet. Dus dan toch graag POSTs.

En liever nu dan over een maand want hoe langer we wachten hoe meer werk het is om de endpoints om te zetten.

**Comment by hilkojacobse** [comment]
@michielgkalkman Mee eens. Ik ga ze aanpassen!

**Comment by rvanrest** [comment]
@michielgkalkman in de branch #KV_get_to_post heeft @hilkojacobse de eerste omzetting gedaan van GET naar POST. 
Naar ons beeld gaat een soort gelijke wijziging voor de overige GET ook plaatsvinden. 

Gaarne verifiëren of dit klopt met jouw beeld.

**Comment by michielgkalkman** [comment]
Ok, maar verwacht je nu meerdere wlzIndicatieIds te kunnen opvoeren?

**Comment by rvanrest** [comment]
Alle GETs zijn 1-op-1 naar POSTs. zie: https://github.com/iStandaarden/iWlz-indicatie/blob/KV_get_to_post/api-specificatie/indicatieregister.yaml

**Comment by Jasperkroes** [comment]
Ik heb een PR (#19) aangemaakt met een paar kleine aanpassingen op de yaml.

**Comment by rvanrest** [comment]
Commit naar master
Release v0.9.6
