### ISSUE TITLE
geen Uzovi meer in entiteit WLz indicatie

### ISSUE THREAD

**Issue by ivovanopstal** [iStandaarden/iWlz-indicatie#12]
In een eerdere versie zat de Uzovi in de entiteit 'Wlzindicatie'. Deze is in de huidge versie verdwenen.
Wij als Menzis hebben echter 3 zorgkantoren onder ons beheer. Het is voor ons van belang dat wij niet hoeven te bepalen voor welk zorgkantoor de geraadpleegde wlzindcatie is aan de hand van het vestigingsadres van de cliënt.

Verzoek om of in de entiteit 'Wlzindicatie' de Uzovi terug te doen keren of in de notificatie op een abonnement mee te geven voor welke Uzovi genotificeerd wordt!

**Comment by rvanrest** [comment]
Deze informatie zit in de notificatie. In de notificatie zit een koppeling tussen de Indicatie via WlzIndicatieID en de ontvanger (via ontvangerID) 

zie de RFC0008: https://github.com/iStandaarden/iWlz-RequestForComment/issues/2
