### ISSUE TITLE
omschrijvingen gegevensvelden in volgindicatieverzoeken, notificaties.

### ISSUE THREAD

**Issue by ivovanopstal** [iStandaarden/iWlz-indicatie#13]
Ik zou graag bij de specs in Github een duidelijke omschrijving willen hebben met wat er precies bedoeld wordt met een bepaald veld en waar het voor dient. Bijvoorbeeld Xorgkey. Maar dat geldt voor alle velden.

**Comment by rvanrest** [comment]
De OpenAPI specificatie komt te vervallen. De GraphQL specificatie is de technische vertaling van wat er functioneel in het informatiemodel is beschreven. Uitleg van elementen staat dus daar. 

zie https://informatiemodel.istandaarden.nl  en dan iWlz Indicatie voor verdere uitleg
