### ISSUE TITLE
Wat is X-PSID eigenlijk en wat moet het indicatie register daarmee doen?

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-indicatie#15]
In de endpoints wordt een X-PSID header opgevoerd. Eigenlijk is mij onduidelijk wat deze header betekent en wat het indicatie register er mee moet doen. Kunnen jullie documentatie opnemen in de swagger spec?

Verder komt deze header niet in de iWlz-generiek swagger voor. Is hij eigenlijk wel nodig?

**Comment by hilkojacobse** [comment]
Dit is een placeholder voor het pseudo id van de client. Het is nog niet helemaal duidelijk hoe dit exact gaat werken. Komt wellicht te vervallen

**Comment by michielgkalkman** [comment]
Misschien is het een idee om m nu te verwijderen.

We zien dan wel weer als het er bij komt.

**Comment by hilkojacobse** [comment]
@michielgkalkman Ja, eens. Ga ik doen.

**Comment by hilkojacobse** [comment]
@michielgkalkman PSID verwijderd uit de master branch.
