### ISSUE TITLE
/bopz en /wzd hebben incorrecte responses (denk ik)

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-indicatie#16]
Kijk bijv naar de response van https://petstore.swagger.io/?url=https://raw.githubusercontent.com/iStandaarden/iWlz-indicatie/master/api-specificatie/indicatieregister.yaml#/operations-bopz-getBopz. Die geeft in de swagger ui view:

`(no example available)`

bij de responses.

MrinDoc wil niet eens laden.

**Comment by rvanrest** [comment]
Het lijkt erop dat het probleem met de laatste commits is verholpen. De responses zijn nu niet leeg voor zover wij kunnen beoordelen. Misschien per ongeluk opgelost bij het wegwerken van de validatie errors. Graag even controleren.

**Comment by michielgkalkman** [comment]
In ieder geval zijn de swagger specs weer valide (functioneel kan ik het niet goed beoordelen).

Dank!
