### ISSUE TITLE
0.9.7-pre wzdEinddatumdatum?

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-indicatie#22]
Lijkt dubbelop.

De properties van het WZD object krijgen nu allemaal de prefix wzd. Lijkt overbodig?

Verder staat er ergens: "Nog verder aanvullen"

**Comment by michielgkalkman** [comment]
BTW:
Client kan nooit een niet-natuurlijk persoon zijn, dus daar valt optie 6 bij naamGebruik af.

En naamGebruik (COD700) moet ook verplicht zijn bij ContactPersoon.

**Comment by rvanrest** [comment]
optie 6 van naamGebruik zit in de huidige iStandaard iWlz, de toekomstige is daarop gebaseerd om de overgang mogelijk te houden. Als we 6 willen (laten) verwijderen moet dat ingebracht worden in de reguliere referentiegroep iWlz en moet er bekeken worden of die waarde in andere iStandaarden (imo/iJw/iPgb/iEb) in gebruik is.

Om die reden heb ik die aanpassing niet doorgevoerd. Ik zal wel alvast een opmerking meenemen hierover als regel op het indicatieregister dat 6 niet gebruikt mag worden.
