### ISSUE TITLE
Status headers X-orgKey en x-request-ID

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-indicatie#27]
Hallo,

Wat is de status van deze headers? Kunnen ze er uit als ze niet verplicht zijn?

Met vriendelijke groet,
Michiel

**Comment by rvanrest** [comment]
@hilkojacobse deze header gegevens in de OpenApi specificatie komen niet meer terug in de GraphQL. De OpenApi zal verder niet blijven. 

Is dit issue nu nog actueel?

**Comment by michielgkalkman** [comment]
De openapi spec blijft voorlopig nog van toepassing tussen Vecozo en CIZ. Ik stel voor dat in de openapi spec wordt opgenomen dat alhoewel deze header gegevens nog steeds verplicht zijn, ze niet worden gebruikt en dat deze headers met arbitraire waardes kunnen worden gevuld. Op die manier is dat in iig vastgelegd voor Vecozo en CIZ en hoeven er ook geen code wijzigingen plaats te vinden.
