### ISSUE TITLE
Types GraphQL en openAPI niet gelijk

### ISSUE THREAD

**Issue by stefanbertensvecozo** [iStandaarden/iWlz-indicatie#37]
@removanrest is dit iets wat we nu nog recht moeten trekken?

In GraphQL heet het type ContactGegeven**s**
https://github.com/iStandaarden/iWlz-indicatie/blob/33946b15ddc6bf68dd43b454af1bee31c6c5cdb4/gql-specificatie/Indicatieregister.graphql#L147

In OpenAPI heet het type ContactGegeven
https://github.com/iStandaarden/iWlz-indicatie/blob/33946b15ddc6bf68dd43b454af1bee31c6c5cdb4/api-specificatie/indicatieregister.yaml#L344

**Comment by rvanrest** [comment]
Hi @stefanbertensvecozo, 
er is nu ook een mailwisseling over, maar wat mij betreft niet voornamelijk omdat de OpenApi een tijdelijke variant is, GraphQL is de techniek die voor het netwerkmodel is gekozen. Maar ik kan niet inschatten of het verschil blokkerend is. 

In elk geval zal dan de OpenApi aangepast moeten worden vanwege het tijdelijke karakter van de techniek en omdat is besloten dat de klasse zelf ContactGegevens moet heten.

**Comment by rvanrest** [comment]
Zojuist besproken binnen het koplopersoverleg. 

De Array gaat heten: ContactInformatie
Het object gaat heten: Contactgegevens

vanuit Client en Contactpersoon komt er dan:
```
        contactInformatie:
          $ref: '#/components/schemas/ContactInformatie'
```
dit was 
```
        contactgegevens:
          $ref: '#/components/schemas/ContactGegevens'
```

De array ContactGegevens gaat heten ContactInformatie
```
    ContactInformatie:
      type: array
      properties:
        contactGegeven:
          $ref: '#/components/schemas/ContactGegevens'
      xml:
        name: contactInformatie
```
dit was
```
    ContactGegevens:
      type: array
      properties:
        contactGegeven:
          $ref: '#/components/schemas/ContactGegeven'
      xml:
        name: contactGegevens
```

 Het object ContactGegeven wordt ContactGegevens
```
    ContactGegevens:
      type: object
      properties:
        adres:
          $ref: '#/components/schemas/Adres'
        telefoon:
          $ref: '#/components/schemas/Telefoon'
        email:
          $ref: '#/components/schemas/Email'
      xml:
        name: contactGegevens
```
dit was
```
    ContactGegeven:
      type: object
      properties:
        adres:
          $ref: '#/components/schemas/Adres'
        telefoon:
          $ref: '#/components/schemas/Telefoon'
        email:
          $ref: '#/components/schemas/Email'
      xml:
        name: contactGegeven
```

**Comment by rvanrest** [comment]
merged into master
