### ISSUE TITLE
Omschrijving 404 error codes

### ISSUE THREAD

**Issue by Joristdh** [iStandaarden/iWlz-indicatie#4]
In de huidig spec worden bij aan aantal endpoints 404 codes teruggeven met de volgende omschrijving:
>  Geen xxxxxx gevonden

Wij missen echter een onderscheid tussen "404 Geen xxxxxx gevonden" en "404 Onbekend WLZ indicatie ID". De afzender weet nu niet of er een onbekend wlzindicatieID in het request stond of dat er simpelweg geen entries waren voor de geleverde (en wel bekende) wlzindicatieID.

Bij de ​/wlzindicaties​/{wlzindicatieID}​/client​/** endpoints is dit, in onze ogen, correct gedefinieerd. Hier krijg je een 404 bij een onbekend wlzindicatieID en een 200 met een lege lijst als er geen contactpersonen (bijvoorbeeld) met de wlzindicatieID zijn geassocieerd.

Aangezien een 4xx error wijst op een client side error, lijkt het ons beter om deze code alleen te gebruiken als er door de afzender foutieve data in het request is gezet (e.g. Onbekend Wlz indicatie ID). Indien dit niet het geval is, moet de gevonden data aangeleverd worden met een 2xx status, ook al is dit alleen een lege array.

Ons voorstel is om dezelfde 404 logica toe te passen voor de overige /wlzindicaties endpoints (met uitzondering van de /wlzindicaties​/{wlzindicatieID} endpoint). Een geldig wlzindicatieID zonder geassocieerde data voor de opgevraagde endpoint resulteert dan in een 200 response met [] als body.
Als het toch gewenst is om een aparte status code te hanteren voor een request met een bekend wlzindicatieID maar geen geassocieerde data, dan stellen wij voor om hiervoor 204 No Content te hanteren.

**Comment by rvanrest** [comment]
Bij opvragingen via wlzindicatieID de error omschrijvingen:

1. "404 Geen xxxxxx gevonden" omzetten naar  "404 Onbekend WLZ indicatie ID".
2. "400 Ongeldig ID" omzetten naar "400 Ongeldig WLZ indicatie ID"
