### ISSUE TITLE
WlzindicatieIDs is ten onrechte gewrapped

### ISSUE THREAD

**Issue by michielgkalkman** [iStandaarden/iWlz-indicatie#5]
**Onderdeel wijziging:**
/wlzIndicaties

**Voorstel wijziging:**
Nu wordt

<WlzindicatieIDs>
	<wlzindicatieID>
		<wlzindicatieID>3fa85f64-5717-4562-b3fc-2c963f66afa6</wlzindicatieID>
	</wlzindicatieID>
</WlzindicatieIDs>

geretourneerd, dat kan korter:
<WlzindicatieIDs>
	<wlzindicatieID>3fa85f64-5717-4562-b3fc-2c963f66afa6</wlzindicatieID>
</WlzindicatieIDs>

Met meerdere wlzindicatieIDs wordt dat dan:
<WlzindicatieIDs>
	<wlzindicatieID>3fa85f64-5717-4562-b3fc-2c963f66afa6</wlzindicatieID>
	<wlzindicatieID>3fa85f64-5717-4562-b3fc-2c963f66afa7</wlzindicatieID>
	<wlzindicatieID>3fa85f64-5717-4562-b3fc-2c963f66afa8</wlzindicatieID>
	
</WlzindicatieIDs>

**Comment by hilkojacobse** [comment]
@michielgkalkman Kan het zijn dat een deel van je comment is weggevallen? Het is me nu niet helemaal duidelijk wat je bedoelt.

Groet,

Hilko

**Comment by michielgkalkman** [comment]
Ja, op 1 of andere manier werd  de xml entities er door github er uit gehaald.

```
<WlzindicatieIDs>
	<wlzindicatieID>
		<wlzindicatieID>3fa85f64-5717-4562-b3fc-2c963f66afa6</wlzindicatieID>
	</wlzindicatieID>
</WlzindicatieIDs>
```

Zou misschien omgezet kunnen worden naar:

```
<WlzindicatieIDs>
	<wlzindicatieID>3fa85f64-5717-4562-b3fc-2c963f66afa6</wlzindicatieID>
</WlzindicatieIDs>
```

Is iets compacter
